import jsPDF from "jspdf"

interface ResumeAnalysisData {
  score: number
  fileName: string
  analysisDate: string
  sections: {
    name: string
    score: number
    feedback: string[]
    recommendations: string[]
  }[]
  keywordAnalysis: {
    found: string[]
    missing: string[]
    suggestions: string[]
  }
  overallFeedback: {
    strengths: string[]
    improvements: string[]
    tips: string[]
  }
}

/*
 * NO EMOJI IN THIS FILE.
 *
 * jsPDF's built-in fonts are WinAnsi-encoded. A single emoji in a string
 * makes jsPDF switch that whole string to UTF-16, so the glyph renders as
 * mojibake ("Keyword Suggestions" came out as a bullet-prefixed run of
 * nulls) and the rest of the line stops being extractable -- which matters
 * because this PDF is a resume artefact people feed to parsers.
 *
 * Measured: an ASCII heading round-trips as "(Keywords Found:)"; the same
 * heading with a leading emoji round-trips as null-interleaved bytes.
 */

export const generateResumeAnalysisPDF = (data: ResumeAnalysisData) => {
  const pdf = new jsPDF()
  let yPosition = 20

  // Helper function to add text with word wrapping
  const addText = (text: string, x: number, y: number, maxWidth = 170, fontSize = 10) => {
    pdf.setFontSize(fontSize)
    const lines = pdf.splitTextToSize(text, maxWidth)
    pdf.text(lines, x, y)
    return y + lines.length * (fontSize * 0.4)
  }

  // Helper function to add a new page if needed
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > 280) {
      pdf.addPage()
      yPosition = 20
    }
  }

  // Header
  pdf.setFillColor(147, 51, 234) // Purple color
  pdf.rect(0, 0, 210, 30, "F")

  pdf.setTextColor(255, 255, 255)
  pdf.setFontSize(24)
  pdf.setFont("helvetica", "bold")
  pdf.text("Resume Analysis Report", 20, 20)

  pdf.setFontSize(12)
  pdf.setFont("helvetica", "normal")
  pdf.text(`Generated by JobSpark AI • ${data.analysisDate}`, 20, 26)

  yPosition = 45

  // Resume Info Section
  pdf.setTextColor(0, 0, 0)
  pdf.setFontSize(16)
  pdf.setFont("helvetica", "bold")
  pdf.text("Resume Information", 20, yPosition)
  yPosition += 10

  pdf.setFontSize(10)
  pdf.setFont("helvetica", "normal")
  yPosition = addText(`File Name: ${data.fileName}`, 20, yPosition)
  yPosition = addText(`Analysis Date: ${data.analysisDate}`, 20, yPosition)
  yPosition += 10

  // Overall Score Section
  checkPageBreak(40)
  pdf.setFillColor(248, 250, 252)
  pdf.rect(15, yPosition - 5, 180, 35, "F")

  pdf.setFontSize(16)
  pdf.setFont("helvetica", "bold")
  pdf.text("Overall ATS Score", 20, yPosition + 5)

  // Score circle representation
  pdf.setFillColor(147, 51, 234)
  pdf.circle(160, yPosition + 15, 12, "F")
  pdf.setTextColor(255, 255, 255)
  pdf.setFontSize(14)
  pdf.setFont("helvetica", "bold")
  pdf.text(`${data.score}%`, 155, yPosition + 17)

  pdf.setTextColor(0, 0, 0)
  pdf.setFontSize(12)
  const scoreLabel = data.score >= 80 ? "Excellent" : data.score >= 60 ? "Good" : "Needs Improvement"
  pdf.text(scoreLabel, 20, yPosition + 20)

  yPosition += 45

  // Section Analysis
  checkPageBreak(20)
  pdf.setFontSize(16)
  pdf.setFont("helvetica", "bold")
  pdf.text("Section Analysis", 20, yPosition)
  yPosition += 15

  data.sections.forEach((section, index) => {
    checkPageBreak(30)

    // Section header
    pdf.setFillColor(243, 244, 246)
    pdf.rect(15, yPosition - 3, 180, 8, "F")

    pdf.setFontSize(12)
    pdf.setFont("helvetica", "bold")
    pdf.text(`${section.name} - ${section.score}%`, 20, yPosition + 2)
    yPosition += 12

    // Feedback
    pdf.setFontSize(10)
    pdf.setFont("helvetica", "normal")
    section.feedback.forEach((feedback) => {
      yPosition = addText(`• ${feedback}`, 25, yPosition)
      yPosition += 2
    })

    // Recommendations
    if (section.recommendations.length > 0) {
      pdf.setFont("helvetica", "bold")
      yPosition = addText("Recommendations:", 25, yPosition)
      pdf.setFont("helvetica", "normal")
      section.recommendations.forEach((rec) => {
        yPosition = addText(`- ${rec}`, 30, yPosition)
        yPosition += 2
      })
    }

    yPosition += 8
  })

  // Keyword Analysis
  checkPageBreak(40)
  pdf.setFontSize(16)
  pdf.setFont("helvetica", "bold")
  pdf.text("Keyword Analysis", 20, yPosition)
  yPosition += 15

  // Found Keywords
  pdf.setFontSize(12)
  pdf.setFont("helvetica", "bold")
  pdf.setTextColor(34, 197, 94) // Green
  pdf.text("Keywords Found:", 20, yPosition)
  yPosition += 8

  pdf.setTextColor(0, 0, 0)
  pdf.setFontSize(10)
  pdf.setFont("helvetica", "normal")
  const foundKeywords = data.keywordAnalysis.found.join(", ")
  yPosition = addText(foundKeywords, 25, yPosition)
  yPosition += 10

  // Missing Keywords
  checkPageBreak(20)
  pdf.setFontSize(12)
  pdf.setFont("helvetica", "bold")
  pdf.setTextColor(239, 68, 68) // Red
  pdf.text("Missing Keywords:", 20, yPosition)
  yPosition += 8

  pdf.setTextColor(0, 0, 0)
  pdf.setFontSize(10)
  pdf.setFont("helvetica", "normal")
  const missingKeywords = data.keywordAnalysis.missing.join(", ")
  yPosition = addText(missingKeywords, 25, yPosition)
  yPosition += 10

  // Keyword Suggestions
  checkPageBreak(20)
  pdf.setFontSize(12)
  pdf.setFont("helvetica", "bold")
  pdf.setTextColor(147, 51, 234) // Purple
  pdf.text("Keyword Suggestions:", 20, yPosition)
  yPosition += 8

  pdf.setTextColor(0, 0, 0)
  pdf.setFontSize(10)
  pdf.setFont("helvetica", "normal")
  data.keywordAnalysis.suggestions.forEach((suggestion) => {
    yPosition = addText(`• ${suggestion}`, 25, yPosition)
    yPosition += 3
  })
  yPosition += 10

  // Overall Feedback
  checkPageBreak(40)
  pdf.setFontSize(16)
  pdf.setFont("helvetica", "bold")
  pdf.text("Detailed Recommendations", 20, yPosition)
  yPosition += 15

  // Strengths
  pdf.setFontSize(12)
  pdf.setFont("helvetica", "bold")
  pdf.setTextColor(34, 197, 94)
  pdf.text("Strengths:", 20, yPosition)
  yPosition += 8

  pdf.setTextColor(0, 0, 0)
  pdf.setFontSize(10)
  pdf.setFont("helvetica", "normal")
  data.overallFeedback.strengths.forEach((strength) => {
    yPosition = addText(`• ${strength}`, 25, yPosition)
    yPosition += 3
  })
  yPosition += 8

  // Areas for Improvement
  checkPageBreak(20)
  pdf.setFontSize(12)
  pdf.setFont("helvetica", "bold")
  pdf.setTextColor(239, 68, 68)
  pdf.text("Areas for Improvement:", 20, yPosition)
  yPosition += 8

  pdf.setTextColor(0, 0, 0)
  pdf.setFontSize(10)
  pdf.setFont("helvetica", "normal")
  data.overallFeedback.improvements.forEach((improvement) => {
    yPosition = addText(`• ${improvement}`, 25, yPosition)
    yPosition += 3
  })
  yPosition += 8

  // Pro Tips
  checkPageBreak(20)
  pdf.setFontSize(12)
  pdf.setFont("helvetica", "bold")
  pdf.setTextColor(147, 51, 234)
  pdf.text("Pro Tips:", 20, yPosition)
  yPosition += 8

  pdf.setTextColor(0, 0, 0)
  pdf.setFontSize(10)
  pdf.setFont("helvetica", "normal")
  data.overallFeedback.tips.forEach((tip) => {
    yPosition = addText(`• ${tip}`, 25, yPosition)
    yPosition += 3
  })

  // Footer
  const pageCount = pdf.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i)
    pdf.setFontSize(8)
    pdf.setTextColor(128, 128, 128)
    pdf.text(`Page ${i} of ${pageCount}`, 20, 290)
    pdf.text("Generated by JobSpark AI - Your AI-Powered Job Search Assistant", 105, 290, { align: "center" })
  }

  return pdf
}
