-- Create blogs table for dynamic news (industry and startup)
create table if not exists public.blogs (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  description text,
  image_url text,
  link text,
  -- section controls which tab the blog appears in
  section text not null default 'industry' check (section in ('industry','startup')),
  created_at timestamptz not null default now()
);

comment on table public.blogs is 'Blogs and news items displayed on the News page';
comment on column public.blogs.section is 'Tab placement: industry | startup';

-- Indexes for faster reads
create index if not exists blogs_created_at_idx on public.blogs (created_at desc);
create index if not exists blogs_section_idx on public.blogs (section);

-- Enable RLS and allow public read access
alter table public.blogs enable row level security;
do $$
begin
  if not exists (
    select 1 from pg_policies 
    where schemaname = 'public' and tablename = 'blogs' and policyname = 'read_blogs_for_all'
  ) then
    create policy read_blogs_for_all on public.blogs
      for select
      using (true);
  end if;
end $$;

-- Optional: allow authenticated users to insert/update/delete
-- Uncomment if you want app users to manage content directly
-- do $$
-- begin
--   if not exists (
--     select 1 from pg_policies 
--     where schemaname = 'public' and tablename = 'blogs' and policyname = 'insert_blogs_authenticated'
--   ) then
--     create policy insert_blogs_authenticated on public.blogs
--       for insert to authenticated
--       with check (true);
--   end if;
--   if not exists (
--     select 1 from pg_policies 
--     where schemaname = 'public' and tablename = 'blogs' and policyname = 'update_blogs_authenticated'
--   ) then
--     create policy update_blogs_authenticated on public.blogs
--       for update to authenticated
--       using (true) with check (true);
--   end if;
--   if not exists (
--     select 1 from pg_policies 
--     where schemaname = 'public' and tablename = 'blogs' and policyname = 'delete_blogs_authenticated'
--   ) then
--     create policy delete_blogs_authenticated on public.blogs
--       for delete to authenticated
--       using (true);
--   end if;
-- end $$;

-- Ensure the table is part of the realtime publication
do $$
declare exists_in_pub boolean;
begin
  select exists(
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'blogs'
  ) into exists_in_pub;
  if not exists_in_pub then
    execute 'alter publication supabase_realtime add table public.blogs';
  end if;
exception when others then
  -- ignore if publication does not exist in local dev or already configured
  null;
end $$;


