-- Analytics events.
--
-- Written by lib/analytics/store.ts (the `supabase` driver). The application
-- aggregates in-process, so this table is an append-mostly event log rather
-- than a set of pre-aggregated counters -- see the note on indexes below.
--
-- WHAT IS AND IS NOT IN HERE
-- --------------------------
-- No IP address, no user agent, no email, no account id. `session_id` is a
-- one-way hash salted with a secret that ROTATES DAILY, so it cannot be
-- reversed to an address and cannot be linked across days. Everything else is a
-- coarse bucket: a device category, a browser family, a country.
--
-- `query` is the only free text, and it is what a visitor typed into a public
-- search box, capped at 200 characters by the application before it arrives.

CREATE TABLE IF NOT EXISTS analytics_events (
  -- Generated by the application (randomUUID) rather than the database, so a
  -- batch insert is one round trip and a retry is naturally idempotent.
  id            uuid PRIMARY KEY,
  type          text        NOT NULL,
  ts            timestamptz NOT NULL DEFAULT now(),

  -- Pseudonymous, daily-rotating. See lib/analytics/identity.ts.
  session_id    text        NOT NULL,

  job_id        text,
  company_slug  text,
  -- Which ATS the posting came from, denormalised so source reports need no join.
  source        text,

  query         text,
  location      text,
  filters       jsonb,
  sort          text,
  result_count  integer,
  page          integer,
  -- 1-based rank in the result list the visitor was looking at.
  position      integer,
  path          text,

  device        text        NOT NULL,
  browser       text        NOT NULL,
  os            text        NOT NULL,
  referrer      text        NOT NULL,
  country       char(2),

  -- Bots are STORED and excluded from metrics, rather than dropped. Dropping
  -- them makes "nobody visited" and "only crawlers visited" indistinguishable,
  -- and those call for very different responses.
  is_bot        boolean     NOT NULL DEFAULT false,

  metadata      jsonb,

  created_at    timestamptz NOT NULL DEFAULT now()
);

-- Values are constrained so a producer bug shows up as a failed insert rather
-- than as a silently unqueryable dimension six weeks later.
ALTER TABLE analytics_events
  ADD CONSTRAINT analytics_events_type_check CHECK (type IN (
    'page_view','search','search_result_impression','job_detail_view','company_view',
    'apply_click','external_redirect','filter_change','sort_change','pagination',
    'save_job','share_job'
  )),
  ADD CONSTRAINT analytics_events_device_check CHECK (device IN ('mobile','tablet','desktop','bot','unknown')),
  ADD CONSTRAINT analytics_events_referrer_check CHECK (referrer IN ('direct','search_engine','social','internal','external','unknown')),
  -- Caps mirror LIMITS in lib/analytics/events.ts. Enforced here too because
  -- the database is the last place that can stop an oversized row.
  ADD CONSTRAINT analytics_events_query_len CHECK (query IS NULL OR length(query) <= 200),
  ADD CONSTRAINT analytics_events_path_len  CHECK (path  IS NULL OR length(path)  <= 256);

-- INDEXES
-- -------
-- Deliberately few. This table is write-heavy and read a handful of times a day
-- by one dashboard, so every extra index is a permanent tax on the common
-- operation to speed up the rare one.
--
-- `ts DESC` is the one that matters: every read is "events in a window", and
-- the retention job is "everything older than X".
CREATE INDEX IF NOT EXISTS analytics_events_ts_idx ON analytics_events (ts DESC);

-- Partial, because the drill-downs that filter by job or employer are always
-- scoped to a window as well, and the vast majority of rows have a job_id --
-- so a plain index would be nearly as large as the table.
CREATE INDEX IF NOT EXISTS analytics_events_job_ts_idx
  ON analytics_events (job_id, ts DESC) WHERE job_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS analytics_events_company_ts_idx
  ON analytics_events (company_slug, ts DESC) WHERE company_slug IS NOT NULL;

-- Zero-result searches are the most valuable query on the table and the rarest
-- rows, which is exactly when a partial index pays for itself.
CREATE INDEX IF NOT EXISTS analytics_events_zero_result_idx
  ON analytics_events (ts DESC) WHERE type = 'search' AND result_count = 0;

-- ROW-LEVEL SECURITY
-- ------------------
-- RLS on with NO policy: this table is reachable only through the service-role
-- key, which bypasses RLS. That is deliberate. Analytics is a report on other
-- people's behaviour, so no browser-side client -- anon or authenticated --
-- should be able to read a single row, and there is no policy that would
-- usefully express "except the admins" when admin-ness is not a database
-- concept in this project (see lib/analytics/admin.ts for why).
ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE analytics_events IS
  'Privacy-conscious product analytics. No IP, user agent, email or account id. '
  'session_id is a daily-rotating one-way hash. Retention is enforced by '
  'scripts/prune-analytics.mjs; see docs/ANALYTICS.md.';
